### ISSUE TITLE
How do I enable Deep-sleep?

### ISSUE THREAD

**Issue by lxz946786639** [luar123/zigbee_esphome#2]
I have roughly looked at your code, but couldn't find the relevant code for Deep sleep? May I ask how to activate it? thanks

**Comment by luar123** [comment]
This should just work using the deepsleep component: https://esphome.io/components/deep_sleep
Also see https://github.com/espressif/esp-zigbee-sdk/tree/46a5a5a6b676738418663009c04ef2e9e08c5b1d/examples/esp_zigbee_sleep/deep_sleep for additional information.

**Comment by lxz946786639** [comment]
Okay, thank you
